name: local-acceptance-stage-java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Release System
        run: docker compose -f docker-compose.yml up -d

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run Smoke Tests
        run: ./gradlew test --tests com.optivem.atddaccelerator.template.systemtest.smoketest.*